---
version: 2.1
orbs:
  ruby: circleci/ruby@2.0.1
  browser-tools: circleci/browser-tools@1.4.3
jobs:
  test:
    macos:
      xcode: 14.3.1
    resource_class: macos.m1.large.gen1
    parallelism: 4
    steps:
      - checkout
      - run:
          name: RSpec split
          command: |            
            circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings

            # bundle exec rspec "${test_files[@]}" --profile 10 --format RspecJunitFormatter --out ~/rspec/rspec.xml --format progress

      - store_test_results:
          path: ~/rspec/rspec.xml

workflows:
  test_build:
    jobs:
      - test

