---
version: 2.1
orbs:
  ruby: circleci/ruby@1.1.1
  profiling: nanophate/docker-profiling@0.3.0
  docker: circleci/docker@2.0.0
jobs:
  test:
    docker:
      - image: circleci/ruby:2.7.4-node-browsers
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - ruby/install-deps
      - ruby/rspec-test
      - profiling/network
  deploy:
    machine:
      image: ubuntu-1604:202007-01
    steps:
      - checkout
      - restore_cache:
         keys:
           - gems-v1-{{ checksum "./Gemfile.lock"  }}-{{ .Branch }}
           - gems-v1-{{ checksum "./Gemfile.lock"  }}
      - docker/build
workflows:
  test_deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test