---
version: 2.1
orbs:
  ruby: circleci/ruby@1.1.1
  heroku: circleci/heroku@1.2.6
jobs:
  test:
    docker:
      - image: circleci/ruby:2.7.4-node-browsers
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - ruby/install-deps
      - run:
          command: |
            mkdir -p /tmp/test-results/rspec
            TESTFILES=$(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)
            sleep 59
            bundle exec rspec $TESTFILES --profile 10 --format RspecJunitFormatter --out /tmp/test-results/rspec/results.xml --format progress --failure-exit-code 0
          name: RSpec Tests
          no_output_timeout: 1m
workflows:
  test_deploy:
    jobs:
      - test
      - heroku/deploy-via-git:
          requires:
            - test
          filters:
            branches:
              only: main
