---
version: 2.1
orbs:
  ruby: circleci/ruby@1.1.1
  heroku: circleci/heroku@1.2.6
jobs:
  test:
    docker:
      - image: circleci/ruby:2.7.4-node-browsers
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - ruby/install-deps
      - ruby/rspec-test
      - run:
        name: 'Clone other repo'
        command: git clone https://github.com/nanophate/minirepo_sample_site
      - run:
        name: 'Checkout out into other repo'
        command: cd minirepo_sample_site
      - run:
        name: 'check if its on other repo'
        command: echo "$(pwd)"
workflows:
  test_deploy:
    jobs:
      - test
      - heroku/deploy-via-git:
          requires:
            - test
          filters:
            branches:
              only: main
