---
version: 2.1
orbs:
  ruby: circleci/ruby@1.1.1
  profiling: nanophate/docker-profiling@0.3.0
  docker: circleci/docker@2.0.0
jobs:
  test:
    docker:
      - image: circleci/ruby:2.7.4-node-browsers
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run:
          name: Skip if [circle skip]
          command: |
            MESSAGE=$(git log -1 HEAD --pretty=format:%s)
            CIRCLESKIP="*[circle skip]*"
            if [[ ${COMMIT_MESSAGE} =~ ${CIRCLESKIP} ]]; then
              circleci-agent step halt
            fi
      - profiling/network
      - ruby/install-deps
      - profiling/network
      - ruby/rspec-test
      - profiling/network
  build:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run: echo "Hello"
workflows:
  test_build:
    jobs:
      - test
      - build:
          requires:
            - test
