---
version: 2.1
orbs:
  ruby: circleci/ruby@1.1.1
  browser-tools: circleci/browser-tools@1.4.1
jobs:
  test:
    docker:
      - image: cimg/ruby:2.7.4-browsers
    parallelism: 3
    steps:
      - checkout
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - run:
          command: |
            google-chrome --version
            chromedriver --version
          name: Check chrome install
      - ruby/install-deps
      - run:
          name: RSpec Tests
          command: |
            mkdir -p /tmp/test-results/rspec
            TESTFILES=$(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)
            echo $TESTFILES
            bundle exec rspec $TESTFILES --profile 10 --format RspecJunitFormatter --out /tmp/test-results/rspec/results.xml --format progress
      - store_test_results:
          path: /tmp/test-results/rspec/results.xml

workflows:
  test_build:
    jobs:
      - test
