---
version: 2.1
orbs:
  ruby: circleci/ruby@1.1.1
jobs:
  test:
    docker:
      - image: circleci/ruby:2.7.4-node-browsers
    parallelism: 3
    steps:
      - checkout
      - ruby/install-deps
      - run:
          name: RSpec Tests
          command: |
            mkdir -p /tmp/test-results/rspec
            TESTFILES=$(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)
            echo $TESTFILES
            bundle exec rspec $TESTFILES --profile 10 --format RspecJunitFormatter --out /tmp/test-results/rspec/results.xml --format progress
      - store_test_results:
          path: /tmp/test-results/rspec/results.xml

workflows:
  test_build:
    jobs:
      - test
