---
version: 2.1
orbs:
  ruby: circleci/ruby@1.1.1
  profiling: nanophate/docker-profiling@0.3.0
jobs:
  test:
    docker:
      - image: circleci/ruby:2.7.4-node-browsers
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    parallelism: 4
    steps:
      - checkout
      - run: ls -la
      - ruby/install-deps
      - run: ls -la
      - ruby/rspec-test
      - profiling/network
workflows:
  test_deploy:
    jobs:
      - test
